---
title: "Data Science Salaries 2020-2024"
author: "Derek Murray"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    dev: pdf
    highlight: tango
  html_document:
    theme: default
    self_contained: true
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    smart: true
    dev: svg
---

```{r setup, include = FALSE}
# DO NOT ALTER THIS CHUNK
# Set knitr options
knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  fig.width = 5,
  fig.asp = 0.618,
  out.width = "70%",
  dpi = 120,
  fig.align = "center",
  cache = FALSE
)
# Load required packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(infer))
suppressPackageStartupMessages(library(modelr))
suppressPackageStartupMessages(library(broom))
# Load dataset
ds_sal <- read.csv("DataScience_salaries_2024.csv") %>%
  type_convert(
    na=combine("", "NA", "PrivacySuppressed")
  )
# Set seed
set.seed(42)
```


### Preprocessing

Filter by "data scientist" job title
```{r}
job_ds <- ds_sal %>%
  filter(job_title == "Data Scientist")
```

Filter data scientists by "US" company location
```{r}
job_ds_loc_us <- job_ds %>%
  filter(company_location == "US")
```




### Visualization

All salaries in USD
```{r}
ds_sal %>%
  ggplot() +
  geom_histogram(aes(x = salary_in_usd))
```

"data scientist" salaries in USD
```{r}
job_ds %>%
  ggplot() +
  geom_histogram(aes(x = salary_in_usd))
```

data scientists in the US in USD
```{r}
job_ds_loc_us %>%
  ggplot() +
  geom_histogram(aes(x = salary_in_usd))
```
test git


### Summary Statistics







### Data Analysis







### Conclusion



